### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_message_class'

### ISSUE THREAD

**Issue by gonzalo-ordas-hs** [lexelby/cloudtrail-logstash#1]
Hi

Running 

```
python cloudtrail-importer.py --sqs-region 'us-east-1' --import-sqs 'cloudtrail' --logstash-server 'localhost:9200' --sqs-number-of-messages 10
```

I get:

```
Traceback (most recent call last):
  File "cloudtrail-importer.py", line 351, in <module>
    messageCount=args.numberOfMessages)
  File "cloudtrail-importer.py", line 267, in getJobFromSQS
    sqsQueue = self.getSQSQueue(sqsQueueName=sqsQueueName, sqsRegion=sqsRegion)
  File "cloudtrail-importer.py", line 212, in getSQSQueue
    sqsQueue.set_message_class(RawMessage)
AttributeError: 'NoneType' object has no attribute 'set_message_class'
```

I can confirm I am export the right credentials, the SQS queue exist and it the the right credentials.

boto (2.38.0)

Any idea/tip?

thanks!!

**Comment by gonzalo-ordas-hs** [comment]
Hi. The issue was really permissions related !!!
